server:
  port: 4060

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/PeterPan-0147/sturdy-potato.git" # TOD: DEAL WITH THIS
          default-label: 'main'