version: '3'


services:
  allservices:
    image: galsie/galcloud-allservices:latest
    ports:
      - "60131:60131"
      - "60132:60132"
      - "60133:60133"
      - "60134:60134"
      - "60135:60135"
      - "60136:60136"
    container_name: gcs-all-services